<a href="https://colab.research.google.com/github/Jaggu268/Neural-Network-Assignment-1/blob/main/ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# employee class code in Python
# class definition

class Employee:

    # data member to count the number of Employees
    count_of_employees = 0
    __name=""
    __family=""
    __salary=0
    __department=""

    # function to set data
    # constructor to intiliaze the name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.__name = name
        self.__family = family
        self.salary = salary
        self.__department = department
        Employee.count_of_employees += 1 #to count number of employees

    #function to calculate the average salary of an employee
    def average_salary(employees):
        total = 0
        for employee in employees:
            total += employee.salary
        return total / Employee.count_of_employees

    #displaying the details of an employee
    def showData(self):
        print("The count of an employee is:",Employee.count_of_employees)
        #print("The Name of an employee is\t:", self.__name)
        #print("The Family of an employee is\t:", self.__family)
        #print("The Department of an employee is\t:", self.__department)
        #print("The Salary of an employee is\t:", self.__salary)

#A subclass which is inherited the properties of the class
class FulltimeEmployee(Employee):
   #intiliazation
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


#main class
def main():
    employees = []
    one = FulltimeEmployee("JAGADEESH ", "fm-pothuru", 120000, "Enginner")  #Declaration
    employees.append(one)  #appending
    two = FulltimeEmployee("RAM", "fm-kamtam", 180000, "Developer")
    employees.append(two)
    three = Employee("KRISHNA", "fm-dhawswarala", 160000, "Manager")
    employees.append(three)
    four = Employee("RK", "Fm-siddavtam", 135000, "fashion")
    employees.append(four)
    Employee.showData(employees)  #showing the data of an employee
    print("Average salary of an employee is:", FulltimeEmployee.average_salary(employees)) #Average salary of an employee


if __name__ == "__main__":
    main()

The count of an employee is: 4
Average salary of an employee is: 148750.0


In [4]:
import numpy as np

#function to replace the maximum value in an array of axis x and y based on the condition
def replace_maxmium(array, replace_value, axis):
    result = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    print(result)


def main():

 #creating a random vector of size 20 which is having in the range of 1-20
    rand20 = np.random.random_sample(20) * 20 + 1
    print(rand20)

    #reshaping the array to 4 by 5 in random20
    rand20_4by5 = rand20.reshape((4, 5))
    print(rand20_4by5)

    replace_maxmium(rand20_4by5, 0, 1)#replacing the max value in each row by zero


if __name__ == "__main__":
    main()

[ 3.67054523 13.77889737  7.58832123 20.68893169 13.58262789  6.77794085
 18.47174109  9.09874701  9.41015549 19.94289606  1.48369621 11.13443314
 19.27227681 10.47294625  1.32554763  6.20037799 12.43723259 14.09071164
 11.44983275  7.41627926]
[[ 3.67054523 13.77889737  7.58832123 20.68893169 13.58262789]
 [ 6.77794085 18.47174109  9.09874701  9.41015549 19.94289606]
 [ 1.48369621 11.13443314 19.27227681 10.47294625  1.32554763]
 [ 6.20037799 12.43723259 14.09071164 11.44983275  7.41627926]]
[[ 3.67054523 13.77889737  7.58832123  0.         13.58262789]
 [ 6.77794085 18.47174109  9.09874701  9.41015549  0.        ]
 [ 1.48369621 11.13443314  0.         10.47294625  1.32554763]
 [ 6.20037799 12.43723259  0.         11.44983275  7.41627926]]
